substitutions:
  device_name: lilygo-ttgo-t
  friendly_name: 'LILYGO TTGO-T Display'

esphome:
  name: $device_name
  friendly_name: $friendly_name

esp32:
  board: esp32dev
  framework:
    type: esp-idf

deep_sleep:
# run_duration: 5min
  id: deepsleep
  esp32_ext1_wakeup:
    mode: ALL_LOW
    pins:
      - number: 0
        allow_other_uses: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_api_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret esphome_ota_key

# WiFi client configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $friendly_name
    password: !secret wifi_password

# Allow provisioning Wi-Fi via serial or web_server
#improv_serial:
# or connect to the fallback ap and get redirected to a web page for wifi credentials
# To have a "next url" for improv serial
#web_server:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# Include custom fonts
font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 42
  - file: "gfonts://Roboto"
    id: roboto_small
    size: 28

sensor:
  - platform: adc              # migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h
    name: "Battery Raw"
    pin: 34
    attenuation: 11db
    id: "VCC"
    update_interval: 10s
    internal: false  
    entity_category: diagnostic

  - platform: template
    name: "Battery"
    id: "vccp"
    unit_of_measurement: '%'
    update_interval: 10s
    entity_category: diagnostic
    lambda: |-
      return ((id(VCC).state / 2.47) * 100);

  # These are examples for including existing sensors known by Home Assistant already.
  # Change the entyty_id: to the sensor entyty_id your Home Assistant instance.
  # Changing the id: values itself requires to adjust the display lambda code too.
  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.easyweatherv1_6_6_outdoor_temperature

  - platform: homeassistant
    id: outdoor_humi
    entity_id: sensor.easyweatherv1_6_6_humidity

  - platform: homeassistant
    id: power
    entity_id: sensor.esphome_web_112a54_power

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      allow_other_uses: true
      mode:
        input: true
        pullup: true
    name: "Button 1"
    id: tdisplay_button_input_1
    on_click: 
      then:
        - light.turn_on: back_light

  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    name: "Button 2"
    id: tdisplay_button_input_2
    on_click: 
      then:
        - deep_sleep.enter
        - light.turn_off: back_light

text:
  - platform: template
    name: Text
    id: text_id
    mode: text
    optimistic: true
    initial_value: "Hello World!"
    icon: "mdi:keyboard-settings-outline"

output:
  - platform: ledc
    pin: 4
    id: gpio_04_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_04_backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

# SPI pins of the ttgo-t module
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

# render on the screen.
display:
  - platform: st7789v
    id: shottimer_display
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    backlight_pin: no
    model: TTGO TDisplay 135x240
    update_interval: 1s
    rotation: 90°
    lambda: |-
      auto black = Color(0, 0, 0);
      auto red = Color(255, 0, 0);
      auto green = Color(0, 255, 0);
      auto blue = Color(0, 0, 255);
      auto turquoise = Color(0, 96, 64);
      auto white = Color(255, 255, 255);

      if (id(tdisplay_button_input_1).state) {
        auto w = it.get_width();
        auto h = it.get_height();

        it.filled_circle(20, 32, 15, black);
        it.filled_circle(40, 32, 15, red);
        it.filled_circle(60, 32, 15, green);
        it.filled_circle(80, 32, 15, blue);
        it.filled_circle(100, 32, 15, white);

        // Draw a cross over entire display
        it.line(0, 0, w, h, green);
        it.line(0, h, w, 0, green);

        // Draw the outline of a rectangle arount the display
        it.rectangle(0, 0, w, h, blue);

        // Draw a filled rectangle
        it.filled_rectangle(2, 2, w-3, h-3, turquoise);

        // Circles! Let's draw one with the center at [20,40] and a radius of 10
        it.circle(20, 40, 10);
        // ... and the same thing filled again
        it.filled_circle(20, 75, 10);

        // Ring and half-ring. First draw the circle with a hole in it
        // at [75,75] with inner raduis of 20 and outer of 30
        it.filled_ring(75, 75, 30, 20);
        // and a "gauge": half-ring that is partially filled.
        // Same position and size but 80% filled left to right
        it.filled_gauge(75, 75, 30, 20, 80);

        // Triangles... Let's draw the outline of a triangle from the [x,y] coordinates of its three points
        // [25,5], [100,5], [80,25]
        it.triangle(25, 5, 100, 5, 80, 25);
        // and a filled triangle !
        it.filled_triangle(115, 5, 95, 25, 125, 70);

        // Regular Polygons? Let's draw a filled, pointy-topped hexagon inscribed in a circle
        // centered on [170,45] with a radius of 20
        it.filled_regular_polygon(170, 45, 20, EDGES_HEXAGON);
        // and the outline of flat-topped octagon around it!
        it.regular_polygon(170, 45, 40, EDGES_OCTAGON, VARIATION_FLAT_TOP);
        // Need to rotate the polygon, or retrieve the coordinates of its vertices? Check the API!
      } else {
        if (id(outdoor_temp).state) {
          it.printf(0, 0, id(roboto_small), green, TextAlign::TOP_LEFT, "%0.1f°C", id(outdoor_temp).state);
        }

        if (id(outdoor_humi).state) {
          it.printf(it.get_width(), 0, id(roboto_small), blue,TextAlign::TOP_RIGHT, "%0.0f%%", id(outdoor_humi).state);
        }

        if (id(power).state) {
          it.printf(0, 135, id(roboto_small), red,TextAlign::BOTTOM_LEFT,"%0.0f W", id(power).state);
        }

        it.print(it.get_width()/2, it.get_height()/2, id(roboto), white, TextAlign::CENTER, id(text_id).state.c_str());
      }