substitutions:
  device_name: esp32-cam
  friendly_name: 'ESP32 CAM'

esphome:
  name: $device_name

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: info

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_api_key

# Allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret esphome_ota_key

# WiFi client configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$(friendly_name) Hotspot"
    password: !secret hotspot_password

# Allow provisioning Wi-Fi via serial or web_server
improv_serial:
# or connect to the fallback ap and get redirected to a web page for wifi credentials
# To have a "next url" for improv serial
web_server:
  port: 80

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

psram:

i2c:
  id: i2c_bus
  sda: GPIO26
  scl: GPIO27
  scan: false

# Example configuration entry
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_id: i2c_bus
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  # Image settings
  name: My ESP32-CAM 
  vertical_flip: false
  horizontal_mirror: false
  max_framerate: 5fps
  jpeg_quality: 10
  resolution: 1024x768

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

## GPIO_4 is the flash light pin
light:
  - platform: binary
    output: gpio_4
    name: flashlight
